import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope", // Tailwind custom variable configuration-er jonno
  weight: ["400", "500", "700", "800"], // Projoniyo font weights ekhane track korte পারো
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
    
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
        <body className={`${manrope.className} min-h-full flex flex-col`}>
        <Navbar></Navbar>
        <main>{children}</main>
        <Footer></Footer>
        <Toaster position="top-right" />

        </body>
    </html>
  );
}
